packages:
  - '.'
  - 'docs'

# to allow transitive dependencies hoisting
shamefullyHoist: true

# https://pnpm.io/settings/build#allowbuilds
allowBuilds:
  # provides fallback repair of platform-specific Rust native engine
  'unrs-resolver': true
  # allows node-gyp build of associated native binaries from local sources
  # disabled because it would require an explicit opt-in
  '@parcel/watcher': false
  # optimization for CLI usage of 'esbuild'
  # disabled because its runtime resolves native binaries itself
  'esbuild': false

# https://pnpm.io/settings/dependency-resolution#minimumreleaseageexclude
minimumReleaseAgeExclude:
  # in case some overrides are necessary...

# https://pnpm.io/settings/dependency-resolution#overrides
# mostly security bumps
overrides:
  'esbuild': '^0.28.1'
  'tar': '^7.5.22'
  'js-yaml': '^4.3.1'
  'svgo': '^4.0.2'
  'brace-expansion@2': '^2.1.4'
  'brace-expansion@5': '^5.0.9'
