packages:
  - '.'
  - 'docs'

# to allow transitive dependencies hoisting
shamefullyHoist: true

# those post-install scripts should run
# (blocked by pnpm by default)
allowBuilds:
  '@parcel/watcher': true
  'esbuild': true
  'unrs-resolver': true

minimumReleaseAgeExclude:
  - '@nuxt/devtools-kit@3.4.0'
  - '@nuxt/devtools-wizard@3.4.0'
  - '@nuxt/devtools@3.4.0'
  - structured-clone-es@2.0.1
